### ISSUE TITLE
feed/notification/design campaign -  separation line

### ISSUE THREAD

**Issue by Marwa7894** [SaTT-Wallet/Frontend#520]
***For campaign notifications (pending - in progress - finished):**

   1) The text should be centered between the date and the campaign preview.
   2) The font size is smaller than the one displayed above.
   3) The date should not be displayed, but rather how long the campaign has been running.
   4) Add the views and budget.

![image](https://github.com/SaTT-Wallet/Frontend/assets/135624031/a8b9d0ce-2f4e-4532-932d-04b235217d52)

***For the separation line:**
   5) On certain screen sizes, the separation line appears very short.

![Sans titre951](https://github.com/SaTT-Wallet/Frontend/assets/135624031/e457dea3-30cc-4b51-acc0-040a61299a4a)

**Comment by hichri-louay** [comment]
Hello @Marwa7894 ,

Currently, we are unable to display views in notifications because we do not have a mechanism in place to track views for adpools. 

To address this issue, I recommend the following steps:

1. Open a feature request or enhancement issue to propose the implementation of a "views" mechanism for adpools.
2. Gather input from the community and stakeholders to determine the requirements and scope of this feature.
3. Plan the implementation, considering design and technical aspects.
4. Once approved, allocate resources and start implementing the "views" feature.

By establishing a "views" mechanism for adpools, we will be able to provide more comprehensive and informative notifications, which can significantly enhance the user experience.

Thank you for your attention to this matter.
