### ISSUE TITLE
Failure to harvest participation link

### ISSUE THREAD

**Issue by Marwa7894** [SaTT-Wallet/Frontend#590]
**Scenario:**

- Participate in a campaign
- Wait for the link to become available to perform the collection
- Try to retrieve the rewards

**Expected result:**

- The harvest is successful

**Actual result:**

- harvest failure

[harvest.webm](https://github.com/SaTT-Wallet/Frontend/assets/135624031/5675607e-d1da-4cef-b251-75f7380332ae)

**Comment by waelhanfi04** [comment]
After conducting an investigation, I discovered that we need to use the same owner's address that created the smart contract for the oracle and identified the issue here. The problem arose when we changed the owner of the campaign without adding the new keystore, resulting in a 'password failed' error in the allowance. To resolve this, I rewrote the smart contract on the testnet and assigned it the same owner's address.
