### ISSUE TITLE
Appearance of the Sign-In Page when Refreshing the Harvest Page

### ISSUE THREAD

**Issue by Marwa7894** [SaTT-Wallet/Frontend#606]
**Preconditions:**
- Already participated in a campaign.
- The link is ready to collect winnings.

**Scenario:**
- Access the "Postfarming" page.
- Click on the "Harvest" status of a link, which redirects to the "Harvest" modal.
- Refresh the page.

**Expected Result:**
- The page should be refreshed without any issues.

**Actual Result:**
- Brief appearance of the "Sign-In" page.

[refresh harvet.webm](https://github.com/SaTT-Wallet/Frontend/assets/135624031/ac349123-6b4a-474d-8ef5-ebe26e9cafad)

**Comment by Marwa7894** [comment]
The problem is still relevant, and this time around, the appearance of the "sign in" page persists
[Capture vidéo du 13-10-2023 18:28:21.webm](https://github.com/SaTT-Wallet/Frontend/assets/135624031/6f294571-eb81-484c-8900-3acce9b10b8c)

**Comment by waelhanfi04** [comment]
[SaTT - Smart advertising Transaction Token.webm](https://github.com/SaTT-Wallet/Frontend/assets/79511539/bf78eba6-d257-4573-b208-0a474743beec)

I successfully resolved the issue by taking the following steps: 

I identified that the problem was related to server-side rendering and traced it back to the 'dist' folder on the server. I proceeded to delete the 'dist' folder and then executed the 'ng build' command once again. As a result, the issue was promptly fixed, and the application now functions as intended. This solution effectively addressed the problem caused by server-side rendering.
