### ISSUE TITLE
Retrieve Budget Failure

### ISSUE THREAD

**Issue by Marwa7894** [SaTT-Wallet/Frontend#632]
**Preconditions:**
- A campaign must be available to retrieve earnings.

**Scenario:**
- Access the campaign.
- Click on the "Retrieve Budget" button.
- Enter the "transaction password."
- Click on "Confirm."

Expected Result:
- The budget retrieval is successful.

Actual Result:
- Budget retrieval failed; the retrieved amount is not added to the wallet.
- The "Retrieve Budget" button remains visible on both the campaign page and the feed page.

[get gains.webm](https://github.com/SaTT-Wallet/Frontend/assets/135624031/40cb24c6-ab25-4eba-976d-f35f44716818)

**Comment by waelhanfi04** [comment]
@Marwa7894  The campaign from which you are attempting to retrieve the budget was originally created using an older smart contract. As a result, you encountered an error related to a "campaign owner mismatch." This error occurred because the credentials used for this campaign are no longer valid. After modifying the keystore of the campaign owner, we recommend testing the budget retrieval process with a new campaign to ensure the correct credentials are being used.
